#!/bin/bash
# USAGE: start|stop|status|logs
#
case "$1" in
update)
echo "# =========================================
echo "Updaing WPUbuntu."
/wpu/init.d/update.sh
;;
add)
echo "Stopping WPUbuntu."
/wpu/init.d/add.sh
;;
logs)
echo "See the logs of the LifeRay Web Portal."
tail -f /wpu/log/log
;;
status)
# Check to see if the process is running
ps aux|grep -i wpubuntu
;;

*)
echo “WPUbuntu”
echo $”Usage: $0 {add|delete|logs|manage|update}”
exit 1
esac
exit 0

